free pbuf for dns query before query goes onto work queue
openziti/ziti-tunnel-sdk-c pull request #128
Opened 2021-03-19 18:43 UTC by scareything

Don't retain the pbuf for dns queries for the entire duration of the query.

2021-03-19 18:45 UTC, dovholuknf approved these changes

2021-03-19 19:06 UTC, smilindave26 commented
Update to latest C SDK while you're in there?

2021-03-22 12:47 UTC, ekoby commented on lib/ziti_tunnel.c
>      int rc = tnlr_ctx->dns->query(tnlr_ctx->dns, p->payload, p->len, send_dns_resp, rr);
this is not safe, there is no guarantee that query is a synchronous operation, `fallback_cb` is always called on a worker thread.

You need to copy payload into `resolve_req`

2021-03-22 12:48 UTC, ekoby requested changes
need to copy payload into resolve_req

2021-03-22 13:08 UTC, ekoby approved these changes

2021-03-22 13:24 UTC, merged